version: "3.8"

services:
  web:
    build: .
    ports:
      - "8000:8000"
      - "5678:5678"
    volumes:
      - ./app:/app/app
      - ./uploads:/app/uploaded_assets
      - ./alembic:/app/alembic
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
